# ~/.config/hypr/hyprlock.conf

# Define color variables at the top
# BACKGROUND
background {
    monitor =
    path = ~/Pictures/5826798.jpg
    blur_passes = 3
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# GENERAL
general {
}

# Profile-Photo
image {
    monitor =
    path = ~/Pictures/IMG_9869_cropped.png
    size = 70
    rounding = -1
    border_size = 0
    position = 0, 200
    halign = center
    valign = bottom
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, 0.70)
    font_size = 25
    font_family = SF Pro Display Bold
    position = 0, 350
    halign = center
    valign = center
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = rgba(216, 222, 233, 0.70)
    font_size = 110
    font_family = SF Pro Display Bold
    position = 0, 250
    halign = center
    valign = center
}

# USER
label {
    text = $USER 
    color = white
    font_size = 13
    font_family = SF Pro Display 
    position = 0, -370
    halign = center
    valign = center
}

label {
    text = $FPRINTPROMPT
    color = rgba(216, 222, 233, 0.80)
    font_size = 13
    font_family = SF Pro Display Regular 
    position = 0, -420
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 45
    rounding = 50
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    fade_timeout = 1000
    font_family = SF Pro Display Regular 
    placeholder_text = <span foreground="##ffffff99">Enter Password</span>
    hide_input = false
    position = 0, -470
    halign = center
    valign = center
    check_color = rgba(255, 255, 255, 0.2)
    fail_color = rgba(255, 100, 100, 0.2)
}

auth {
    fingerprint {
        enabled = true
        ready_message = Touch ID or Enter Password
        present_message = Scanning...
        retry_delay = 250
    }
}
