hl.on("hyprland.start", function()
	hl.exec_cmd("bash ~/.config/hypr/xdg-portal-hyprland")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("/usr/local/bin/hp-camera-fix.sh")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("elephant")
	hl.exec_cmd("hyprctl setcursor macOS 24")
	hl.exec_cmd("quickshell -c /usr/share/tide-island")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd(
		"sleep 0.5 && awww img ~/Pictures/Wallpapers/5826807.jpg --transition-type center --transition-step 5 --transition-fps 60"
	)
	hl.exec_cmd("hyprsunset")
hl.workspace("^\\d+$", "exec, fish ~/.config/hypr/scripts/ws-anim-switch.fish")
	-- hl.exec_cmd("ags run ~/.config/ags/bar/app.ts")
	-- hl.exec_cmd("swaybg -m fill -i ~/Pictures/5826802.jpg")
end)
