# Terminal settings
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ',xterm-256color:Tc'
# Undercurl support
set -as terminal-overrides ',:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -g default-shell /usr/bin/fish

# General settings
unbind C-b
set -g prefix C-a
bind C-a send-prefix
setw -g mode-keys vi
set -g base-index 1
setw -g pane-base-index 1
setw -g mouse on
set -s escape-time 0
set -g focus-events on
set -g automatic-rename on
set-option -g set-titles on
set-option -gw xterm-keys on
set -g status-interval 5
set -g renumber-windows on
set -g history-limit 50000

# Window navigation
bind -n M-h previous-window
bind -n M-l next-window

# Pane splitting (opens in current path)
bind | split-window -h -c "#{pane_current_path}"
bind % split-window -v -c "#{pane_current_path}"
unbind '"'

# Reload config (Prefix + r)
bind r source-file ~/.config/tmux/tmux.conf\; display-message "Config reloaded!"

#Copy mode improvements
bind v copy-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# Session management
# bind S choose-session                      # Prefix + S: list and switch sessions
bind N command-prompt "new-session -s '%%'"  # Prefix + N: create new named session
bind K confirm-before -p "Kill session #S? (y/n)" kill-session  # Prefix + K: kill current session
bind X confirm-before -p "Kill all other sessions? (y/n)" "kill-session -a"  # Prefix + X: kill all except current

# Plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'aserowy/tmux.nvim'
set -g @plugin 'tmux-plugins/tmux-resurrect'


# Plugin settings
set -g @yank_action "copy-pipe"
# tmux-resurrect settings
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# Message style
set -g message-style "fg=yellow,bg=#040405"
set -g message-command-style "fg=yellow,bg=#040405"

# Pane style
set -g pane-border-style "fg=#040406" 
set -g pane-active-border-style "fg=#040405" 
set-window-option -g pane-border-status off

# Status bar style
set -g status-style "fg=yellow,bg=#040405"
set -g status-left "#[fg=#B2BBCA,bg=#040405]#[fg=#040405,bg=#B2BBCA] #{session_windows}#[fg=#B2BBCA,bg=#040405]  "
set -g status-right "#[fg=#B2BBCA,bg=#040405] #S #[fg=#B2BBCA,bg=#040405] #[fg=black,bg=#B2BBCA]󱫋 #{session_attached}#[fg=#B2BBCA,bg=#040405]"
set -g status-left-length 100
set -g status-position top
set -g status-justify centre

# Window style
set -g window-status-style "fg=#B2BBCA,bg=#040405"
set -g window-status-format "#[fg=default,bg=#040405] #[fg=default,bg=#040405]#W"
set -g window-status-separator "  "
set -g window-status-current-format "#[fg=#D89784,bg=#040405]  #[fg=#B2BBCA,bg=#040405]#W"

# Initialize TPM (keep this at the very bottom)
run '~/.config/tmux/plugins/tpm/tpm'
